server:
  port: 8080
  servlet:
    context-path: /scutcom

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
    username: root
    password: 223BBCbbc661
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000


mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    use-generated-keys: true #自动生成主键（id）
    map-underscore-to-camel-case: true #驼峰命名
  type-aliases-package: "com.scut.community.entity" #这个的作用是在xml中不用总是写全限定类名



